source 'https://rubygems.org'
# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"
gem 'webrick'
gem 'thin'
gem 'falcon'
gem 'puma'
gem 'dotenv'
gem 'httparty'
gem 'json'
gem "minitest"
gem "pry"
gem "rake"
gem "capybara"
gem "rack"
